app.py
import flask
import os
import logging

from flask import Flask
from roku import Roku


def make_app():
  app = Flask(__name__)
  app.config.from_object('config')

  # setup loggers
  gunicorn_logger = logging.getLogger('gunicorn.info')
  app.logger.handlers = gunicorn_logger.handlers
  app.logger.setLevel(gunicorn_logger.level)

  from views import views
  app.register_blueprint(views)
  roku = Roku(app.config['ROKU_TV_IP'])
  app.roku = roku
  app.glogger = gunicorn_logger
  return app


if __name__ == '__main__':
  app = make_app()
  app.run(host='0.0.0.0', debug=True)

views.py
from flask import (
    flash,
    current_app,
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
)

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def index():
  power_is_on = current_app.roku.power_on
  current_roku_app = current_app.roku.get_active_app()
  installed_apps = current_app.roku.apps
  return render_template(
      'index.html',
      power_is_on=power_is_on,
      current_app=current_roku_app,
      installed_apps=installed_apps,
  )


@views.route('/launch/<app_id>', methods=['POST'])
def launch(app_id):
  current_app.roku.launch_app(app_id=app_id)
  flash(f'Launching {app_id}')
  return redirect(url_for('views.index'))


@views.route('/power/<value>', methods=['POST'])
def power(value):
  """ switch the power of the device """
  if value == 'on':
    current_app.roku.turn_on()
  elif value == 'off':
    current_app.roku.turn_off()
  else:
    raise ValueError(f'value shoud be one of on, off')
  return redirect(url_for('views.index'))


@views.after_request
def log_request(response):
  current_app.logger.info('Incoming request from %s: %s %s -> %s', request.remote_addr,
                          request.method, request.path, response.status)
  return response

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Controller for RokuTV device">
    <meta name="author" content="Pablo Llueca">

    <title>RokuTV Controller</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    
  </head>
  <body>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>

</html>
<Paste>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

  <div class="row justify-content-md-center title-div">
      <h1 class="mt-5">Roku Controller</h1>
  </div>

  <div class="row">
    <p>Roku Tv is on: {{ power_is_on }}</p>
  </div>

  <div class="row">
    {% if not power_is_on %}
    <form action={{ url_for("views.power", value="on")}} method="post">
      <input type="submit" class="btn btn-success" value="Power On">
    </form>
    {% else %}
      <form action={{ url_for("views.power", value="off")}} method="post">
        <input type="submit" class="btn btn-danger" value="Power Off">
      </form>
    {% endif %}
  </div>

  <div class="row">
    <p>Current channel: {{ current_app.name }}</p>
  </div>

  <div class="row">
    <table class="tg">
      <tr>
        <th class="tg-0lax">channel</th>
        <th class="tg-0lax">type</th>
        <th class="tg-0lax">is active</th>
        <th class="tg-0lax">activate</th>
      </tr>
      {% for app in installed_apps %}
      <tr>
        <td class="tg-0lax">{{ app.name }}</td>
        <td class="tg-0lax">{{ app.app_type }}</td>
        <td class="tg-0lax">{{ app.name == current_app.name }}</td>
        <td class="tg-0lax">
          <form action={{ url_for("views.launch", app_id = app.id) }}  method="post" id="nameform">
            <input type="submit" class="btn btn-primary" name="btn_launch {{app.name}}" value=Launch />
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}